### ISSUE TITLE
Adaptar al Sistema de Diseño Dominicano

### ISSUE THREAD

**Issue by gustavovalverde** [opticrd/cuenta-unica-registry#107]
Utilizar la librería que está en NPM https://github.com/opticrd/sdd-kit

**Comment by Victor1890** [comment]
Url no disponible

**Comment by marluanespiritusanto** [comment]
Hola @Victor1890. Sucede que de momento ese repositorio es privado. Sin embargo, @gustavovalverde  hace referencia a implementar los componentes de [este](https://www.npmjs.com/package/@ogticrd/ui-kit) paquete.
