### ISSUE TITLE
Capturar correo después de X cantidad de intentos

### ISSUE THREAD

**Issue by gustavovalverde** [opticrd/cuenta-unica-registry#22]
Si el usuario no se puede validar después X cantidad de intentos, pedirle su correo en la pantalla de biometría, para poder contactarle u ofrecerle un proceso alterno

**Comment by marluanespiritusanto** [comment]
La resolución de este issue será trabajada inmediatamente si dividan las responsabilidades del proyecto y la posible implementación de Ballerine.
