### ISSUE TITLE
improve steppers micro-interaction and ui/ux

### ISSUE THREAD

**Issue by DeyvisonGarcia** [opticrd/cuenta-unica-registry#42]
Colocar los colores de los estado en el stepper, como esta en el figma, cuando esta completo, cuanod esta activo y cuando esta sin completar/inactivo.

Colocar divisor de contenido del steppe y el contenido del form.

![image](https://github.com/opticrd/auth-registry-frontend/assets/90786530/a118cc6f-b84d-44c2-81a6-d47983f3e060)

**Como esta en el figma**
![image](https://github.com/opticrd/auth-registry-frontend/assets/90786530/dac61dcf-eaaa-431c-89c3-68abd138161c)

**Comment by gustavovalverde** [comment]
Fixed
