### ISSUE TITLE
Change to SVG illustration and logotypes UI/UX

### ISSUE THREAD

**Issue by DeyvisonGarcia** [opticrd/cuenta-unica-registry#43]
Cambiar todos las imagenes, logos e ilustraciones a SVG, ahora están en png y se están deformando.

Link repositorio de recursos graficos.
[https://opticgobdo.sharepoint.com/:f:/s/LID/EgFv9nkwd19LvZCXR9COVm4B9-EVDIQ_9Rw2R0Gz7bQyng?e=O8MyoR](url)

**Comment by gustavovalverde** [comment]
Fixed by 2de7b91101e1b13002e8abe072f45946146b81cd
