### ISSUE TITLE
Dominio https://cuentaunica.gob.do/ no responde

### ISSUE THREAD

**Issue by robertlluberes** [opticrd/cuenta-unica-registry#80]
He intentado acceder al dominio https://cuentaunica.gob.do/ que está mencionado en la documentación del repositorio, pero no se encuentra disponible. Es necesario que se verifique si el dominio está operativo o, en caso contrario, se actualice la documentación para reflejar el dominio correcto.

**Comment by marluanespiritusanto** [comment]
Hola @robertlluberes, muchas gracias por tu reporte. El dominio https://cuentaunica.gob .do aún no está disponible para uso público. A partir del despliegue oficial de la primera versión del proyecto —aproximadamente la primera semana de septiembre— el dominio estará disponible. Sin embargo, estaremos agregando el comentario a la documentación para evitar futuras confusiones.
